# Generated by Django 4.0.6 on 2024-04-01 08:29

from django.db import migrations, models
import django.db.models.deletion
import shortuuid.main


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('genres', '0001_initial'),
        ('authors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=256, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=256, null=True)),
                ('deleted_by', models.CharField(blank=True, max_length=256, null=True)),
                ('id', models.CharField(default=shortuuid.main.ShortUUID.uuid, max_length=20, primary_key=True, serialize=False)),
                ('deleted', models.BooleanField(default=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, null=True)),
                ('number_of_copies', models.IntegerField(default=0)),
                ('available_copies', models.IntegerField(default=0)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=256, null=True)),
                ('isbn', models.CharField(blank=True, max_length=100, null=True)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authors.author')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='genres.genre')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
